# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from ast import keyword
from PIL import Image
import sys,re,os
from PyQt5 import QtCore,QtWidgets,QtGui
from PyQt5.QtCore import Qt,QPoint
from PyQt5.QtWidgets import QApplication,QMainWindow,QInputDialog,QWidget,QMessageBox
import requests
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import pic
import cv2
import base64
import numpy as np
import datetime


key_status = 0

class Ui_MainWindow(QMainWindow):
    _startPos = None
    _endPos = None
    _isTracking = False
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 620)
        MainWindow.setWindowFlags(Qt.FramelessWindowHint)  # 无边框
        rect = QRectF(0, 0, self.width(), self.height())
        path = QPainterPath()
        path.addRoundedRect(rect, 10, 10)
        polygon = path.toFillPolygon().toPolygon()
        region= QRegion(polygon)
        self.setMask(region)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(870, 620))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgb(238,238,238);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_3.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(90, 90))
        self.label.setMaximumSize(QtCore.QSize(90, 90))
        self.label.setStyleSheet("border-radius:15;\n"
"background-color: rgb(141,141,141);\n"
"margin:10 5 5 10;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMinimumSize(QtCore.QSize(200, 20))
        self.label_2.setMaximumSize(QtCore.QSize(200, 20))
        self.label_2.setStyleSheet("margin-left:10;\n"
"color:rgb(141,141,141);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setMinimumSize(QtCore.QSize(200, 20))
        self.label_26.setMaximumSize(QtCore.QSize(200, 20))
        self.label_26.setStyleSheet("margin-left:10;\n"
"color:rgb(105,105,105);")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_22.addWidget(self.label_26)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setMinimumSize(QtCore.QSize(30, 20))
        self.label_5.setMaximumSize(QtCore.QSize(30, 20))
        self.label_5.setStyleSheet("margin-left:10;\n"
"image: url(:/icon/res/home-2.png);\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_15.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setMinimumSize(QtCore.QSize(150, 20))
        self.label_4.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("\n"
"color:rgb(250,13,1);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_15.addWidget(self.label_4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        spacerItem = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setMinimumSize(QtCore.QSize(30, 20))
        self.label_7.setMaximumSize(QtCore.QSize(30, 20))
        self.label_7.setStyleSheet("margin-left:10;\n"
"image: url(:/icon/res/explain.png);\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setMinimumSize(QtCore.QSize(150, 20))
        self.label_6.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:black;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        spacerItem1 = QtWidgets.QSpacerItem(6, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setMinimumSize(QtCore.QSize(30, 20))
        self.label_16.setMaximumSize(QtCore.QSize(30, 20))
        self.label_16.setStyleSheet("margin-left:10;\n"
"image: url(:/icon/res/user.png);\n"
"")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setMinimumSize(QtCore.QSize(150, 20))
        self.label_15.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:black;")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        spacerItem2 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem2)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setMinimumSize(QtCore.QSize(30, 20))
        self.label_18.setMaximumSize(QtCore.QSize(30, 20))
        self.label_18.setStyleSheet("margin-left:10;\n"
"image: url(:/icon/res/mic.png);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setMinimumSize(QtCore.QSize(150, 20))
        self.label_17.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:black;")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_19.addWidget(self.label_17)
        self.verticalLayout_12.addLayout(self.horizontalLayout_19)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setMinimumSize(QtCore.QSize(200, 20))
        self.label_25.setMaximumSize(QtCore.QSize(200, 20))
        self.label_25.setStyleSheet("margin-left:10;\n"
"color:rgb(105,105,105);")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_6.addWidget(self.label_25)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(30, 20))
        self.label_20.setMaximumSize(QtCore.QSize(30, 20))
        self.label_20.setStyleSheet("margin-left:10;\n"
"image: url(:/icon/res/download.png);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_18.addWidget(self.label_20)
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setMinimumSize(QtCore.QSize(150, 20))
        self.label_19.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:black;")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        spacerItem4 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem4)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_21 = QtWidgets.QLabel(self.frame_3)
        self.label_21.setMinimumSize(QtCore.QSize(30, 20))
        self.label_21.setMaximumSize(QtCore.QSize(30, 20))
        self.label_21.setStyleSheet("margin-left:10;\n"
"image: url(:/icon/res/fabulous.png);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_17.addWidget(self.label_21)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMinimumSize(QtCore.QSize(150, 20))
        self.label_3.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:black;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_17.addWidget(self.label_3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        spacerItem5 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem5)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_38.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setMinimumSize(QtCore.QSize(30, 20))
        self.label_23.setMaximumSize(QtCore.QSize(30, 20))
        self.label_23.setStyleSheet("margin-left:10;\n"
"image: url(:/icon/res/add-bold.png);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_38.addWidget(self.label_23)
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        self.label_22.setMinimumSize(QtCore.QSize(150, 20))
        self.label_22.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:black;")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_38.addWidget(self.label_22)
        self.verticalLayout_12.addLayout(self.horizontalLayout_38)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem6)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_47 = QtWidgets.QLabel(self.frame_3)
        self.label_47.setMinimumSize(QtCore.QSize(35, 25))
        self.label_47.setMaximumSize(QtCore.QSize(25, 25))
        self.label_47.setStyleSheet("image: url(:/icon/res/sign-out.png);margin-left:10;margin-bottom:5;\n"
"")
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_16.addWidget(self.label_47)
        self.label_46 = QtWidgets.QLabel(self.frame_3)
        self.label_46.setMinimumSize(QtCore.QSize(35, 25))
        self.label_46.setMaximumSize(QtCore.QSize(25, 25))
        self.label_46.setStyleSheet("image: url(:/icon/res/setting.png);margin-right:10;margin-bottom:5;")
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_16.addWidget(self.label_46)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.verticalLayout_2.addLayout(self.verticalLayout_12)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setStyleSheet("padding:0;")
        self.page_5.setObjectName("page_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget = QtWidgets.QWidget(self.page_5)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setMinimumSize(QtCore.QSize(30, 30))
        self.label_9.setMaximumSize(QtCore.QSize(30, 30))
        self.label_9.setStyleSheet("background-color:rgb(250,250,250);border-radius:15;\n"
"image: url(:/icon/res/fanye.png);padding:5;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setMinimumSize(QtCore.QSize(30, 30))
        self.label_10.setMaximumSize(QtCore.QSize(30, 30))
        self.label_10.setStyleSheet("background-color:rgb(250,250,250);border-radius:15;\n"
"image: url(:/icon/res/fanye-2.png);padding:5,5,5,5;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.frame_11 = QtWidgets.QFrame(self.widget)
        self.frame_11.setMinimumSize(QtCore.QSize(280, 30))
        self.frame_11.setMaximumSize(QtCore.QSize(280, 30))
        self.frame_11.setStyleSheet("background-color:rgb(250,250,250);border-radius:15;\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setMinimumSize(QtCore.QSize(30, 30))
        self.label_11.setMaximumSize(QtCore.QSize(30, 30))
        self.label_11.setStyleSheet("background-color:rgb(250,250,250);border-radius:15;\n"
"padding:5,5,5,5;\n"
"image: url(:/icon/res/sousuo.png);\n"
"\n"
"")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setAttribute(Qt.WA_MacShowFocusRect, 0)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lineEdit_2.setStyleSheet("border:0;\n"
"hover{background-color:rgb(0,0,0)\n"
"\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_12.addWidget(self.lineEdit_2)
        self.horizontalLayout_3.addWidget(self.frame_11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget_2.setStyleSheet("")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("pandding:0;")
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout.addWidget(self.frame)
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5.addWidget(self.frame_2)
        self.stackedWidget_2.addWidget(self.page_2)
        self.horizontalLayout_13.addWidget(self.stackedWidget_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setMinimumSize(QtCore.QSize(30, 30))
        self.label_12.setMaximumSize(QtCore.QSize(30, 30))
        self.label_12.setStyleSheet("background-color:rgb(250,250,250);border-radius:15;\n"
"image: url(:/icon/res/icon-.png);padding:5;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setMinimumSize(QtCore.QSize(30, 30))
        self.label_13.setMaximumSize(QtCore.QSize(30, 30))
        self.label_13.setStyleSheet("background-color:rgb(250,250,250);border-radius:15;\n"
"image: url(:/icon/res/icon_yingyongguanli.png);padding:5;")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setMinimumSize(QtCore.QSize(100, 30))
        self.label_14.setMaximumSize(QtCore.QSize(100, 30))
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setStyleSheet("background-color:rgb(250,250,250);border-radius:15;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        spacerItem8 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_13 = QtWidgets.QFrame(self.widget)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_13.setStyleSheet("border:0;\n"
"")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_27 = QtWidgets.QLabel(self.frame_13)
        self.label_27.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_21.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.frame_13)
        self.label_28.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_21.addWidget(self.label_28)
        self.label_24 = QtWidgets.QLabel(self.frame_13)
        self.label_24.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_21.addWidget(self.label_24)
        self.verticalLayout_9.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_29 = QtWidgets.QLabel(self.frame_13)
        self.label_29.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_23.addWidget(self.label_29)
        self.label_31 = QtWidgets.QLabel(self.frame_13)
        self.label_31.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_23.addWidget(self.label_31)
        self.label_30 = QtWidgets.QLabel(self.frame_13)
        self.label_30.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_23.addWidget(self.label_30)
        self.verticalLayout_9.addLayout(self.horizontalLayout_23)
        self.verticalLayout_11.addWidget(self.frame_13)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setMinimumSize(QtCore.QSize(30, 30))
        self.label_8.setMaximumSize(QtCore.QSize(30, 30))
        self.label_8.setStyleSheet("background-color:rgb(250,250,250);border-radius:15;\n"
"image: url(:/icon/res/tongzhi-2.png);padding:5;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.frame_8 = QtWidgets.QFrame(self.widget)
        self.frame_8.setMinimumSize(QtCore.QSize(200, 30))
        self.frame_8.setMaximumSize(QtCore.QSize(200, 30))
        self.frame_8.setStyleSheet("background-color:rgb(250,250,250);border-radius:15;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7.addWidget(self.frame_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_9 = QtWidgets.QFrame(self.widget)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 215))
        self.frame_9.setStyleSheet("background-color:rgb(250,250,250);border-radius:15;\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_32 = QtWidgets.QLabel(self.frame_9)
        self.label_32.setMinimumSize(QtCore.QSize(100, 110))
        self.label_32.setMaximumSize(QtCore.QSize(100, 110))
        self.label_32.setStyleSheet("border-radius:10;\n"
"background-color: rgb(196, 196, 196);\n"
"margin-top:10;")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_24.addWidget(self.label_32)
        self.verticalLayout_13.addLayout(self.horizontalLayout_24)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_33 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_33.setFont(font)
        self.label_33.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_33.setStyleSheet("")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_25.addWidget(self.label_33)
        self.verticalLayout_15.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_34 = QtWidgets.QLabel(self.frame_9)
        self.label_34.setStyleSheet("color:rgb(105,105,105);")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_27.addWidget(self.label_34)
        self.verticalLayout_15.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_9)
        self.horizontalSlider.setStyleSheet("")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickInterval(0)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_32.addWidget(self.horizontalSlider)
        self.verticalLayout_15.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_39 = QtWidgets.QLabel(self.frame_9)
        self.label_39.setStyleSheet("image: url(:/icon/res/shangyishou.png);margin-bottom:5;")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_35.addWidget(self.label_39)
        self.label_35 = QtWidgets.QLabel(self.frame_9)
        self.label_35.setStyleSheet("image: url(:/icon/res/zanting.png);margin-bottom:5;")
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_35.addWidget(self.label_35)
        self.label_37 = QtWidgets.QLabel(self.frame_9)
        self.label_37.setStyleSheet("image: url(:/icon/res/xiayishou.png);margin-bottom:5;")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_35.addWidget(self.label_37)
        self.verticalLayout_15.addLayout(self.horizontalLayout_35)
        self.verticalLayout_13.addLayout(self.verticalLayout_15)
        self.horizontalLayout_8.addWidget(self.frame_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 300))
        self.scrollArea.setStyleSheet("border:0;")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 246, 320))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 320))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 320))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_36.setMinimumSize(QtCore.QSize(0, 28))
        self.label_36.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_36.setStyleSheet("background-color:rgb(250,250,250);border-radius:5;padding-left:5;\n"
"")
        self.label_36.setObjectName("label_36")
        self.verticalLayout_17.addWidget(self.label_36)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_41.setMinimumSize(QtCore.QSize(0, 28))
        self.label_41.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_41.setStyleSheet("background-color:rgb(250,250,250);border-radius:5;padding-left:5;")
        self.label_41.setObjectName("label_41")
        self.verticalLayout_17.addWidget(self.label_41)
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_40.setMinimumSize(QtCore.QSize(0, 28))
        self.label_40.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_40.setStyleSheet("background-color:rgb(250,250,250);border-radius:5;padding-left:5;")
        self.label_40.setObjectName("label_40")
        self.verticalLayout_17.addWidget(self.label_40)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_45.setMinimumSize(QtCore.QSize(0, 28))
        self.label_45.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_45.setStyleSheet("background-color:rgb(250,250,250);border-radius:5;padding-left:5;")
        self.label_45.setObjectName("label_45")
        self.verticalLayout_17.addWidget(self.label_45)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_44.setMinimumSize(QtCore.QSize(0, 28))
        self.label_44.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_44.setStyleSheet("background-color:rgb(250,250,250);border-radius:5;padding-left:5;")
        self.label_44.setObjectName("label_44")
        self.verticalLayout_17.addWidget(self.label_44)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_43.setMinimumSize(QtCore.QSize(0, 28))
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_43.setStyleSheet("background-color:rgb(250,250,250);border-radius:5;padding-left:5;")
        self.label_43.setObjectName("label_43")
        self.verticalLayout_17.addWidget(self.label_43)
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_42.setMinimumSize(QtCore.QSize(0, 28))
        self.label_42.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_42.setStyleSheet("background-color:rgb(250,250,250);border-radius:5;padding-left:5;")
        self.label_42.setObjectName("label_42")
        self.verticalLayout_17.addWidget(self.label_42)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_38.setMinimumSize(QtCore.QSize(0, 28))
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_38.setStyleSheet("background-color:rgb(250,250,250);border-radius:5;padding-left:5;")
        self.label_38.setObjectName("label_38")
        self.verticalLayout_17.addWidget(self.label_38)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.verticalLayout_4.addLayout(self.verticalLayout_8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5.addWidget(self.widget)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedWidget.addWidget(self.page_6)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.show()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "个性签名"))
        self.label_26.setText(_translate("MainWindow", "发现音乐"))
        self.label_4.setText(_translate("MainWindow", "首页"))
        self.label_6.setText(_translate("MainWindow", "专辑"))
        self.label_15.setText(_translate("MainWindow", "歌手"))
        self.label_17.setText(_translate("MainWindow", "播客"))
        self.label_25.setText(_translate("MainWindow", "我的音乐"))
        self.label_19.setText(_translate("MainWindow", "本地与下载"))
        self.label_3.setText(_translate("MainWindow", "我喜欢的音乐"))
        self.label_22.setText(_translate("MainWindow", "创建歌单"))
        self.label_14.setText(_translate("MainWindow", "换一换"))
        self.label_33.setText(_translate("MainWindow", "song name"))
        self.label_34.setText(_translate("MainWindow", "author"))
        self.label_36.setText(_translate("MainWindow", "Song-Album-Author"))
        self.label_41.setText(_translate("MainWindow", "Song-Album-Author"))
        self.label_40.setText(_translate("MainWindow", "Song-Album-Author"))
        self.label_45.setText(_translate("MainWindow", "Song-Album-Author"))
        self.label_44.setText(_translate("MainWindow", "Song-Album-Author"))
        self.label_43.setText(_translate("MainWindow", "Song-Album-Author"))
        self.label_42.setText(_translate("MainWindow", "Song-Album-Author"))
        self.label_38.setText(_translate("MainWindow", "Song-Album-Author"))
    def mouseMoveEvent(self, e: QMouseEvent):  # 重写移动事件
        self._endPos = e.pos() - self._startPos
        self.move(self.pos() + self._endPos)

    def mousePressEvent(self, e: QMouseEvent):
        if e.button() == Qt.LeftButton:
            self._isTracking = True
            self._startPos = QPoint(e.x(), e.y())

    def mouseReleaseEvent(self, e: QMouseEvent):
        if e.button() == Qt.LeftButton:
            self._isTracking = False
            self._startPos = None
            self._endPos = None

    '''服务器ip和端口，若是本地运行，ip则为localhost或127.0.0.1'''
    def serve_ip(self):
        ip = "http://106.54.191.240:3000"
        return ip


    def decode_base64_cv_img(self,base64_data):
        global cookie_s
        img = base64.b64decode(base64_data)
        img_array = np.fromstring(img, np.uint8)  # 转换np序列
        img_raw = cv2.imdecode(img_array, cv2.IMREAD_COLOR)  # 转换Opencv格式BGR
        img_gray = cv2.imdecode(img_array, cv2.IMREAD_GRAYSCALE)  # 转换灰度图
        path = "/Users/apple/Desktop/netmusic/app/.hyper_music.txt"
        while(1):
            cv2.imshow("img bgr", img_raw)
            code = self.qr_code_check()[2]
            r = self.qr_code_check()[3]
            if code == "800":
                cv2.destroyAllWindows()
                print("二维码过期，请重新登陆")
                break
            if code == "803":
                cv2.destroyAllWindows()
                #print(r.text)
                cookie_s=re.findall(r'"cookie":"(.+?)"}',r)[0]
                Note=open(path,mode='w')
                Note.write(cookie_s)
                print("登陆成功")
                break
            if code == "801":
                print("等待扫码")

            if code == "802":
                print("等待授权")


            #print(qr_code_check()[0],code)
            cv2.waitKey(1000)
    def get_qr_img(self):
        keywords = "/login/qr/create"
        get_link = self.serve_ip()+keywords+"?"+"key="+self.get_qr_key()+"&qrimg=true"+"&"+self.get_time_update()
        r = requests.get(get_link)
        img_base64 = re.findall(r'base64,(.+?)"}',r.text)
        self.decode_base64_cv_img(img_base64[0])

    '''时间戳：年月日时分秒'''
    def get_time_update(self):
        i = datetime.datetime.now()
        time = "timestamp="+str(i.year)+str(i.month)+str(i.day)+str(i.hour)+str(i.minute)+str(i.second)
        return time

    '''获取登陆状态'''
    def get_login_statu(self):
        keywords = "/login/status"
        get_link = self.serve_ip()+keywords
        r = requests.get(get_link)
        code = re.findall(r'code":(.+?),"',r.text)[0]
        #print(get_link,r.text)
        if code == "200":
            return "logined"
        else:
            return "loginull"
    '''获取用户uid'''
    def get_uid(self):
        if self.get_login_statu() == "logined":
            keywords = "/user/account"
            get_link = self.serve_ip()+keywords+"?cookie="+self.read_cookie_file()
            r = requests.get(get_link)
            uid = re.findall(r'id":(.+?),"userName":',r.text)[0]
            return uid
        else:
            print("未登陆或登录异常！")
            return 0

    '''检查二维码状态'''
    def qr_code_check(self):

        keywords = "/login/qr/check"
        get_link = self.serve_ip()+keywords+"?key="+ self.get_qr_key() +"&"+self.get_time_update()
        r = requests.get(get_link)
        qr_code_status = re.findall(r'message":"(.+?)","cookie"',r.text)[0]
        code = re.findall(r'code":(.+?),"message"',r.text)[0]
        return qr_code_status,get_link,code,r.text


    def get_qr_key(self):
        global key_status,key_new
        keywords="/login/qr/key"
        get_link = self.serve_ip()+keywords+"?"+self.get_time_update()
        r = requests.get(get_link)
        if  key_status == 0:
            key = re.findall(r'":"(.+?)"}',r.text)
            key_status = 1
            key_new = key[0]
        return key_new

    '''获取登陆二维码图片的base64编码'''
    def get_qr_img(self):
        keywords = "/login/qr/create"
        get_link = self.serve_ip()+keywords+"?"+"key="+self.get_qr_key()+"&qrimg=true"+"&"+self.get_time_update()
        r = requests.get(get_link)
        img_base64 = re.findall(r'base64,(.+?)"}',r.text)
        self.decode_base64_cv_img(img_base64[0])


    '''检查是否存在本地cookie'''
    def check_cookie_file(self):
        path = "/Users/apple/Desktop/netmusic/app/.hyper_music.txt"
        a = os.path.exists(path)
        if a!=True:
            print("不存在cookie")
            self.get_qr_img()

    '''从文件读取cookie'''
    def read_cookie_file(self):
        path = "/Users/apple/Desktop/netmusic/app/.hyper_music.txt"
        with open(path, "r", encoding='utf-8') as f:  #打开文本
            data = f.read()   #读取文本
            #print(data)
        return data

    '''获取账号信息，头像，签名等'''
    def get_account_info(self):
        path = "/Users/apple/Desktop/netmusic/app/.avatar.jpg"
        keywords = "/user/account"
        get_link = self.serve_ip()+keywords+"?cookie="+self.read_cookie_file()
        r = requests.get(get_link)

        '''头像显示'''
        avatar = re.findall(r'"avatarUrl":"(.+?)","backgroundImgId',r.text)[0]
        a_link = requests.get(avatar)
        with open(path, "wb") as f:  
            data = f.write(a_link.content)   
        pic_org = Image.open(path)
        pic_new = pic_org.resize((75, 75), Image.ANTIALIAS)
        pic_new.save(path)   # 将修改后的图像存储到新的路径中

        self.label.setStyleSheet("border-radius:15;\n"
            "background-color: rgb(141,141,141);\n"
            "margin:10 5 5 10;\n"
            "background-image: url(/Users/apple/Desktop/netmusic/app/.avatar.jpg);")

        '''个性签名显示'''
        signature =  re.findall(r'signature":(.+?),"createTime"',r.text)[0]
        self.label_2.setText(signature)
        #print(r.text)

    '''获取推荐歌单并显示'''
    def get_gedan_rec(self):
        #path = "/Users/apple/Desktop/netmusic/app/catch/.res_1.jpg"
        keywords = "/recommend/resource"
        get_link = self.serve_ip()+keywords+"?cookie="+self.read_cookie_file()
        r = requests.get(get_link)
        rec_name = re.findall(r'"picUrl":"(.+?)","playcount',r.text)
        for i in range(0,len(rec_name)):
           
            path = "/Users/apple/Desktop/netmusic/app/catch/.res_"+str(i)+".jpg"
            a_link = requests.get(rec_name[i])
            with open(path, "wb") as f:  
                data = f.write(a_link.content)   
            pic_org = Image.open(path)
            pic_new = pic_org.resize((117, 120))
            pic_new=pic_new.convert('RGB')
            pic_new.save(path,quality=95)   # 将修改后的图像存储到新的路径中
            
        self.label_27.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;\n"
        "background-image: url(/Users/apple/Desktop/netmusic/app/catch/.res_1.jpg);")
        self.label_28.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;\n"
        "background-image: url(/Users/apple/Desktop/netmusic/app/catch/.res_2.jpg);")
        self.label_24.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;\n"
        "background-image: url(/Users/apple/Desktop/netmusic/app/catch/.res_3.jpg);")
        self.label_29.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;\n"
        "background-image: url(/Users/apple/Desktop/netmusic/app/catch/.res_4.jpg);")
        self.label_31.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;\n"
        "background-image: url(/Users/apple/Desktop/netmusic/app/catch/.res_5.jpg);")
        self.label_30.setStyleSheet("background-color:rgb(250,250,250);border-radius:10;\n"
        "background-image: url(/Users/apple/Desktop/netmusic/app/catch/.res_6.jpg);")
        #print(rec_name)
        



if __name__ == "__main__":
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.check_cookie_file()
    ui.get_account_info()
    ui.get_gedan_rec()
    sys.exit(app.exec_())
